### ISSUE TITLE
Demeteorization process fails

### ISSUE THREAD

**Issue by theworkflow** [onmodulus/docker-build-meteor#13]
Many reports of demeteorization process failing due to ENOSPC. Reported originally by a Modulus user [here](https://github.com/onmodulus/modulus-cli/issues/107#issuecomment-211881487).

```
Uploading project...
Upload progress [===================] 100%
Deploying project into Meteor runtime...
Starting build.
Creating directories for build environment.
Downloading source.
Executing build.
Demeteorizing application...
mop, this is your first time using Meteor!
Installing a Meteor distribution in your home directory.
######################################################################## 100.0%

/mnt/home/.meteor/packages/meteor-tool/.1.3.0_3.p3s7qv++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/lib/node_modules/meteor-promise/promise_server.js:116
      throw error;
            ^
Error: ENOSPC, mkdir '/mnt/tmp/.tmpl0uhx2/less-2.5.6/plugin.compileLessBatch.os/npm/node_modules/meteor/babel-runtime/node_modules/regenerator/node_modules/commoner/node_modules/glob/node_modules/minimatch/node_modules/brace-expansion/node_modules/concat-map/example'
Conversion failed.
```

**Comment by nickpolet** [comment]
Has there been any update on this? Deploying is now impossible with modulus.

**Comment by lytstephen** [comment]
Yep same issue here. Got quite a few updates wanted to deploy now. Please help.

**Comment by jackboberg** [comment]
@harlanj is working on #12, which makes a lot of changes and optimizations to how we install and use node/npm/meteor. Really hoping to get an RC today and release a new beta ASAP.

That said, I find it hard to believe any issue with how we are installing dependencies could result in eating 4GB and causing `ENOSPC`.

@nickpolet @lytstephen 
Are you all seeing similar tools/dependencies when you are hitting these errors? Always less/babel related?

**Comment by nickpolet** [comment]
My issues have all been resolved now. Deployment runs smoothly.

**Comment by epeng5** [comment]
I ran into the same issue as of 2 hours ago.

Here's the full error:

`/mnt/home/.meteor/packages/meteor-tool/.1.3.0_3.w96oy++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/lib/node_modules/meteor-promise/promise_server.js:116
      throw error;
            ^
Error: ENOSPC, open '/mnt/home/.meteor/packages/templating/.build677280..1.1.7.yrd79y++os+web.browser+web.cordova/web.browser/.builder-tmp-file.624822'
Conversion failed.`

**Comment by lytstephen** [comment]
just deployed twice, confirm working fine for me too, with meteor 1.3.2.2. Thanks.

**Comment by theworkflow** [comment]
@nickpolet @lytstephen Can you try redeploying? We pushed out new build and run images today. Also to use the new run image you need to stop/start your app.

**Comment by nickpolet** [comment]
@harlanj Seems to be working now. I had to update to 1.3.2.4 to get it working. When I tried deploying with meteor 1.3.1.1 it didn't work, and the build process on the server was using 1.3.2.4. Is there a way to force which meteor version is used on the server?

I was assuming that the build process would use the release.js file to determine which meteor version to be used, but it didn't seem to register when I tried with 1.3.1.1.

Thanks for pushing out the new build image.

**Comment by theworkflow** [comment]
@nickpolet Our build servers use `meteor@1.3.2.4`. We use some flags that are only compatible with `v1.3x`. Meteor is very heavy and they have no way of installing a specific version. When we install Meteor it automatically installs the latest version. We do identify the version in your application, but we only require that your app be `v1.3` or greater.

**Comment by nickpolet** [comment]
@harlanj Ok, thanks for clearing that up. 

My only concern with that is some projects it's quite difficult to keep perfectly up-to-date due the size of some projects. If there a meteor release which breaks any api compatibility, applications might fail to build and deploy. I understand that it is much better to use the most current version of frameworks, but time sometimes makes that very difficult, especially if you only want to deploy simple changes up to the server.

Would opening up a ticket on the meteor repo to allow for specific version installs help this issue at all? Or is the build process version specific?

**Comment by theworkflow** [comment]
@nickpolet That would actually be great. If you check their install script, they source the version from a CDN or other web service. Even though it's not hardcoded, it's automated out of the user's control. The build process only wants your bundle to use any version of `meteor@1.3.x`. It cares about that and that there is a `.meteor` directory in the root of your bundle.

**Comment by nickpolet** [comment]
@harlanj Yea I noticed that the install script uses a CDN which doesn't seem to store older versions. Just the latest version. And the script seems to be statically served, which makes it tricky to pass in variables to the script. But this is something that should really be sorted. I didn't realise it was so tricky to install specific versions without having the install the latest version, then downgrading to an app specific version. Very annoying. I'll open an issue on meteor.

The script _can_ be modified to pull in release versions from github, but this seems like a ridiculous workaround to something which should really be covered by their install script.

**Comment by theworkflow** [comment]
Yup. Very cumbersome. Keep us posted on the issue you create on Meteor though! Would love to follow it. 👍
