### ISSUE TITLE
Incomplete build

### ISSUE THREAD

**Issue by theworkflow** [onmodulus/docker-build-meteor#15]
Issue reported on [Modulus CLI issues #110](https://github.com/onmodulus/modulus-cli/issues/110#issuecomment-212187615) by @flean

```
Compressing project...
7.3 MB written
Uploading project...
Upload progress [===================] 100%
Deploying project into Meteor runtime...

[✓] bundle running at xxxxxxx.onmodulus.net
```

Nothing happens, it just does that. No provisioning or building environment...

**Comment by flean** [comment]
Any updates?

**Comment by jackboberg** [comment]
@flean We are prepping a new release candidate right now. This error seems more like a build server failure though, is this reproducible?

**Comment by flean** [comment]
Meteor Projects @ 1.3.2.2 in Meteor enviorments, nothing happens. No build

**Comment by flean** [comment]
Not sure if you guys changed anything, I tested again and it's working now.

**Comment by epeng5** [comment]
@jackboberg have you guys pushed out the new release candidate? If not, what's the eta?

**Comment by jackboberg** [comment]
@epeng5 I believe new build/run images will be pushed to production today.

**Comment by theworkflow** [comment]
@epeng5 New images have been pushed today. To use the latest `run` image you need to stop/start your application. Let us know how it goes!

**Comment by epeng5** [comment]
@harlanj @jackboberg Works like a charm! Thanks!

**Comment by theworkflow** [comment]
@epeng5 great! Glad your issues are resolved!
