### ISSUE TITLE
Deploy issue

### ISSUE THREAD

**Issue by ivanthemeh** [onmodulus/docker-build-meteor#16]
I have been having some off and on issues deploying for about a week now and I am at my wits end with this. The most recent error was: 
   `/mnt/home/.meteor/packages/meteor-  tool/.1.3.1.17izmgn++os.linux.x86_64+web.browser+web.cordova/mt-                      os.linux.x86_64/dev_bundle/lib/node_modules/meteor-promise/promise_server.js:116
      throw error;`
so then I updated the cli and now Im just getting "error uploading"

**Comment by vjain20** [comment]
I am having a similar problem

```
Upload progress [===================] 100%
Deploying project into Meteor runtime...
Starting build.
Creating directories for build environment.
Downloading source.
Executing build.
Demeteorizing application...
mop, this is your first time using Meteor!
Installing a Meteor distribution in your home directory.
######################################################################## 100.0%

/mnt/home/.meteor/packages/meteor-tool/.1.3.1.5kme59++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/lib/node_modules/meteor-promise/promise_server.js:116
      throw error;
            ^
undefined
Conversion failed.
Build failed, reverting project.

[✓] techshare running at techshare-61762.onmodulus.net
~/WebstormProjects/techshare> modulus --version
6.0.0
~/WebstormProjects/techshare> meteor --version
Meteor 1.3.1
```

**Comment by theworkflow** [comment]
@ivanthemeh @vjain20 we pushed out new build and run images today. Can you try to redeploy and let me know if you're still having problems? Also, to use the new run image you need to stop/start your application.

**Comment by vjain20** [comment]
Hi,
The latest modulus build has created some problem with the deployment.  Now
whenever I am deploying my app and restarting it, I see the following:

> meteor-dev-bundle@0.0.0 start /mnt/app/bundle/programs/server
> 
> node ../../main

Could not read template file: welcome.html mailer

Now using node v0.10.41 (npm v3.8.6)

Found package.json: ./.modulus/nvm/package.json

ERROR: No start script found. There is no application to run.

Now using node v0.10.41 (npm v3.8.6)

Found package.json: ./.modulus/nvm/package.json

ERROR: No start script found. There is no application to run.

Now using node v0.10.41 (npm v3.8.6)

Found package.json: ./.modulus/nvm/package.json

ERROR: No start script found. There is no application to run.

Now using node v0.10.41 (npm v3.8.6)

Found package.json: ./.modulus/nvm/package.json

ERROR: No start script found. There is no application to run.

Now using node v0.10.41 (npm v3.8.6)

Found package.json: ./.modulus/nvm/package.json

ERROR: No start script found. There is no application to run.

Now using node v0.10.41 (npm v3.8.6)

Found package.json: ./.modulus/nvm/package.json

On Mon, Apr 25, 2016 at 1:15 PM, Jeremiah Harlan notifications@github.com
wrote:

> @ivanthemeh https://github.com/ivanthemeh @vjain20
> https://github.com/vjain20 we pushed out new build and run images
> today. Can you try to redeploy and let me know if you're still having
> problems? Also, to use the new run image you need to stop/start your
> application.
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> https://github.com/onmodulus/docker-build-meteor/issues/16#issuecomment-214506014

## 

Thanks
Vaibhav Jain

**Comment by jackboberg** [comment]
@vjain20 It looks like you are running the old `run-meteor` image. Can you try deploying to a new project, or fully stop/start your existing build?

**Comment by theworkflow** [comment]
@vjain20 You will need to stop/start your project to use the updated run image. It is a requirement for the current build image.

**Comment by vjain20** [comment]
Thanks. Its working now. I thought restarting should be enough.

On Tue, Apr 26, 2016 at 7:15 AM, Jeremiah Harlan notifications@github.com
wrote:

> @vjain20 https://github.com/vjain20 You will need to stop/start your
> project to use the updated run image. It is a requirement for the current
> build image.
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> https://github.com/onmodulus/docker-build-meteor/issues/16#issuecomment-214759322

## 

Thanks
Vaibhav Jain

**Comment by theworkflow** [comment]
Unfortunately, a restart does not pick up the updated run image. 😢
