### ISSUE TITLE
Meteor 1.3.3.1 doesn’t work yet with modulus meteor build.

### ISSUE THREAD

**Issue by tomtom2110** [onmodulus/docker-build-meteor#21]
i was allready in contact with modulus Support regarding this Topic. modulus Support wrote: 
JUN 21, 2016  |  08:42AM EDT 
David Berger replied:
Hey Thomas,
Meteor 1.3.3.1 doesn’t work yet with our meteor build.
As I previously noted you should be using Meteor 1.3.2.4.
Were you using version 6 of the CLI when you deployed? --> yes, i'am useing CLI ver 6
If so, submit an issue here: https://github.com/onmodulus/docker-build-meteor/issues
A developer will respond to any issue submitted there.
Make sure to note that you have already gone over the issue with support.

Regards, 

David Berger 
Support Engineer 
Our Support Policy 
Modulus | modulus.io 
A Progress Company 
@OnModulus 

> > > error message when i'am deployiny my Meteor Project to modulus and opening the URL via Webbrowser: Unable to connect to any application instances.
> > > my modulus Project: http://simonjuliana-66520.onmodulus.net/

**Comment by theworkflow** [comment]
Hey @tomtom2110 sorry for the late response to your issue. We updated our build image to work with `Meteor@1.3.3.1`. This issue was solved in commit  ea47407. If you're still having this problem can you let me know? If not, feel free to close this issue.
