### ISSUE TITLE
deploy - Cordova error: Plugin "es6-promise-plugin" not found

### ISSUE THREAD

**Issue by theworkflow** [onmodulus/docker-build-meteor#23]
Issue originally reported by @Wade-BuildOtto ([`#124`](https://github.com/onmodulus/modulus-cli/issues/124))

---

I found that it builds when I run the deploy command a second time, odd that it just doesn't ignore it, as it was trying to remove it anyways. I would prefer to not have to do it twice.

Errors executing Cordova commands:

While removing plugins

com.googlemaps.ios,com.pylonproducts.wifiwizard,cordova-plugin-compat,cordova-plugin-device,cordova-plugin-geofence,cordova-plugin-geolocation,cordova-plugin-googlemaps,cordova-plugin-meteor-webapp,cordova-plugin-splashscreen,cordova-plugin-statusbar,cordova-plugin-whitelist,cordova-plugin-wkwebview-engine,es6-promise-plugin
from Cordova project:
Cordova error: Plugin "es6-promise-plugin" not found. Already uninstalled?
(If the error message contains suggestions for a fix, note that this may not apply to the Meteor integration. You can try running again with the --verbose option to
help diagnose the issue.)
undefined

[Error] Error: Conversion failed.

**Comment by theworkflow** [comment]
@Wade-BuildOtto once again, we do apologize for the late response. I made a comment on another similar issue (referring to a customer's build failing).

What runtime is your project currently running under? If it's running under the Meteor runtime, then we can try to do some things locally to replicate our build system's environment and `demeteorize` your application. If it's running under the Node.js runtime, what version of the CLI are you using to deploy your application? I ask the later question because depending on what version of the `modulus-cli` you are using, that determines the version of `demeteorizer` that's being used. 

To run some tests, you can refer to a comment I made on a similar issue on this repo [here](https://github.com/onmodulus/docker-build-meteor/issues/22#issuecomment-233965569).

**Comment by theworkflow** [comment]
Issue seems to be resolved. Closing issue.

**Comment by Wade-BuildOtto** [comment]
this was used in a meteor project, I just did a meteor reset and it cleared the issue.
