### ISSUE TITLE
Couldnt Install Packages from npm-shrinkwrap

### ISSUE THREAD

**Issue by marksapp** [onmodulus/docker-build-meteor#32]
I am encountering an issues when deploying - using modulus 6.3.1:
Deploying project into Meteor runtime...
Starting build.
Creating directories for build environment.
Downloading source.
Executing build.
Now using node v4.4.7 (npm v3.10.5)
Initializing Meteor environment.
Using METEOR@1.4.1.1.
Node version 4 specified.
Demeteorizing application...
npm-container: updating npm dependencies -- gm, phantomjs, mkdirp...
=> Errors while initializing project:

While building package npm-container:
error: couldn't install npm packages from npm-shrinkwrap: Command failed:
/mnt/home/.meteor/packages/meteor-tool/.1.4.1_1.uueo8v++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/bin/npm
install
npm ERR! Linux 3.13.0-93-generic
npm ERR! argv
"/mnt/home/.meteor/packages/meteor-tool/.1.4.1_1.uueo8v++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/bin/node"
"/mnt/home/.meteor/packages/meteor-tool/.1.4.1_1.uueo8v++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/bin/npm"
"install"
npm ERR! node v4.5.0
npm ERR! npm  v3.10.6
npm ERR! code ELIFECYCLE

npm ERR! phantomjs@1.9.0-1 install: `node install.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the phantomjs@1.9.0-1 install script 'node install.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the phantomjs package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node install.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs phantomjs
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls phantomjs
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!
/mnt/input/packages/npm-container/.npm/package-new-mccak4/npm-debug.log
npm ERR! Linux 3.13.0-93-generic

**Comment by theworkflow** [comment]
hey @marksapp sorry for missing this. If you're still having this problem can you provide some source code for us to test out? Are you able to `demeteorize` your application locally just to see if it's a problem with our build servers?

**Comment by theworkflow** [comment]
@marksapp I'm going to close this issue for now. If you're still having this problem just reopen it with some details and maybe an example project so we can test it against the build image.
