### ISSUE TITLE
[Error] Unable to copy to storage host

### ISSUE THREAD

**Issue by timmakken** [onmodulus/docker-build-meteor#33]
Im having trouble uploading my projects to modulus since changing to meteor build image.
`modulus deploy --node-version 4
`
resulting in this

Deploying Meteor version 1.4.1.

Compressing project...
10.8 MB written
Uploading project...
Upload progress [===================] 100%
[Error] Unable to copy to storage host

Previously it ended like this:
Initializing Meteor environment.
Using METEOR@1.4.1.1.
Node version 4 specified.
Demeteorizing application...

[✓] myproject running at myproject-0000.onmodulus.net

**Comment by theworkflow** [comment]
@timmakken Sorry for the trouble. The problem that you were experiencing was with our storage servers. That issue is now resolved. If it continues to happen you can open a support request and we will assist you from there.
