### ISSUE TITLE
Use meteor build with --server only flag

### ISSUE THREAD

**Issue by bergerd1** [onmodulus/docker-build-meteor#6]
> I think you need to modify the build script on your meteor deploy so that the build does -- server-only
> 
> If you do that it will skip the mobile builds but retain the parts that we need if we are targeting mobiles and life will be Awesome

**Comment by jackboberg** [comment]
Since we use [`demeteorizer`](/onmodulus/demeteorizer), this change would have to happen there.

**Comment by flean** [comment]
Any update with this? I still can't deploy. How do I get the modulus cli with the meteor environment to use the `--server-only`. I'm hoping this will fix my issues.

**Comment by flean** [comment]
Trying to deploy a meteor 1.3+ app that also targets android fails to build in the meteor environment. I've deployed my app without targeting mobile and it works. When I add mobile it fails... I'm not an expert but I'm pretty certain that the `docker-build-meteor` is missing the `--server-only` flag when it demeteorizes the bundle.

I'm using the latest modulus cli and demeteorizer

**Comment by elchiapp** [comment]
Yes, the only way, for now, is to remove the mobile platforms altogether, deploy to Modulus and then readd the platforms. Waiting for a fix.

**Comment by jackboberg** [comment]
An updated image is available, please let us know if you are still having issues.

@lambdacomplete @flean
